### PR TITLE
feat(autoware_adapi_v1_msgs): add detect area

### PR DESCRIPTION
**Pull request by tkhmy**
## Description
- add msgs for detect area

## Related links
https://github.com/autowarefoundation/autoware/issues/3225#issuecomment-1409926655
https://github.com/autowarefoundation/autoware-documentation/pull/333

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
Detect Area name is too ambiguous. I proposed https://github.com/autowarefoundation/autoware/discussions/3342 to change the naming in Autoware Universe. Is it ok to continue this after we decide on the name?

**Comment by tkhmy** [comment]
> Detect Area name is too ambiguous. I proposed [autowarefoundation/autoware#3342](https://github.com/orgs/autowarefoundation/discussions/3342) to change the naming in Autoware Universe. Is it ok to continue this after we decide on the name?

@xmfcx You mean the detection_area from the planning?

Yes, I do agree that the detection_area need to be rename.

For this api, actually I mean for the detect area that planning is looking at, it will cover the following area
- blind spot
- crosswalk
- detection_area
- intersection
- merge_from_private
- no_stopping_area
- walkway

I think this api also need to rename to a better phrase

**Comment by tkhmy** [comment]
> Hmm, then maybe `PlanningZone` and `PlanningZoneArray` could be good message names. What do you think?
> 
> cc: @TakaHoribe @mitsudome-r @isamu-takagi @mehmetdogru @takayuki5168 @kosuke55

Ya, I think `PlanningZone` and `PlanningZoneArray` will be a good message name. If no commend, I think I will change to it

**Comment by tkhmy** [comment]
@xmfcx Hi, sorry for the long wait, I changed the naming to `PlanningArea`, I think `Area` will be much common phrases for autoware.

**Comment by tkhmy** [comment]
@isamu-takagi cc: @yabuta @yuasabe 
As this task is not going to develop by my side, so I will close this pr.

**Pull request closed without merging**
