### PR TITLE
feat(autoware_adapi_v1_msgs): add routing option for goal modification

### PR DESCRIPTION
**Pull request by isamu-takagi**
## Description

Add option for the goal modification (https://github.com/autowarefoundation/autoware/issues/3406).

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kosuke55 — APPROVED** [review]
LGTM

**Comment by mitsudome-r** [comment]
@isamu-takagi Are there any documentation about how this option should be used?
I want to make sure that user doesn't have to come to this PR description to know what each field means.

I would also like to see more details about explanation as well, possibly with example situation:

DISABLE
* Forbid goal modification by Autoware. 
* The goal position is not changed under any situation. <- Is this also true in emergency situation?
* E.g., When there is an obstacle on the given goal pose, Autoware will wait until obstacle is removed.

ENABLE
* Allow goal modification by Autoware
* The goal position can be changed by Autoware according to the situation
* E.g., When there is an obstacle on the given goal pose, Autoware will look for open space nearby for a new goal.

SYSTEM
> The above DISABLE and ENABLE are selected according to system settings.
I'm not sure what this is for? Who selects the mode and how?

**Comment by isamu-takagi** [comment]
> I'm not sure what this is for. Who selects the mode and how?

@mitsudome-r  Use this when the user doesn't really care about goal modification. The system default settings determined by the service and environment are used.

**Comment by isamu-takagi** [comment]
> The goal position is not changed under any situation. <- Is this also true in emergency situation?

For emergency, Autoware will activate MRM and invalidate the normal routing. This option has no effect as goal modification is only for normal routing.

**Comment by mitsudome-r** [comment]
> Use this when the user doesn't care about goal modification. The system default settings determined by the service and environment are used.

What do you mean by "system default settings"? Is it Autoware's planning module's ROS parameter?
Also, if user doesn't care, what's the reason for setting "SYSTEM" and not "ENABLE" (which also let Autoware choose in the end)?

**Comment by isamu-takagi** [comment]
> What do you mean by "system default settings"? Is it Autoware's planning module's ROS parameter?
Also, if user doesn't care, what's the reason for setting "SYSTEM" and not "ENABLE" (which also let Autoware choose in the end)?

It doesn't matter what the system default setting is, such as map attribute or planning component parameters. My assumption is that `ENABLE` will ignore these settings and force goal modification to take effect.

**Comment by isamu-takagi** [comment]
@mitsudome-r https://github.com/autowarefoundation/autoware_adapi_msgs/pull/30/commits/8c86111bdf95e1b0fc4dbcb763b35749527dfddc Change it to bool because it is not currently an essential use case. Add it as another flag if needed.

**Comment by kosuke55** [comment]
@mitsudome-r Could you please check this?

**Comment by mitsudome-r** [comment]
@isamu-takagi 
Could you confirm if this available somewhere in documentation (README of the package or Autoware-Documentation)?

> Are there any documentation about how this option should be used?
I want to make sure that user doesn't have to come to this PR description to know what each field means.

**Comment by mitsudome-r** [comment]
@isamu-takagi 
I've also mentioned in this [comment](https://github.com/autowarefoundation/autoware/issues/3406#issuecomment-1501357694), but if there is possibility of merging it with modified_goal interface, I would like to know if this message has enough information.

**Comment by isamu-takagi** [comment]
>@isamu-takagi
Could you confirm if this available somewhere in documentation (README of the package or Autoware-Documentation)?

Add the document here: https://github.com/autowarefoundation/autoware-documentation/pull/348.

**Pull request merged**
