### PR TITLE
feat(CHANGELOG): bump up version to 1.3.0

### PR DESCRIPTION
**Pull request by youtalk**
## Description

bump up version to 1.3.0

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by youtalk** [comment]
@esteve According to the comment https://github.com/autowarefoundation/autoware_internal_msgs/pull/19#pullrequestreview-2150898334, the tag has not been pushed yet. Once it is merged into the main branch, I plan to manually push the tag to the main branch.

```
$ catkin_prepare_release --bump minor
Prepare the source repository for a release.
Repository type: git
Found packages: autoware_adapi_v1_msgs, autoware_adapi_version_msgs
Prepare release of version '1.3.0' [Y/n]?Y
Trying to push to remote repository (dry run)...
Everything up-to-date
Checking if working copy is clean (no staged changes, no modified files, no untracked files)...
Rename the forthcoming section of the following packages to version '1.3.0': autoware_adapi_v1_msgs, autoware_adapi_version_msgs
Bump version of all packages from '1.2.1' to '1.3.0'
Committing the package.xml files...
[v1.3.0 30d93b5] 1.3.0
 4 files changed, 6 insertions(+), 6 deletions(-)
Creating tag '1.3.0'...
The following commands will be executed to push the changes and tag to the remote repository:
  /usr/bin/git push origin v1.3.0
  /usr/bin/git push origin 1.3.0
Execute commands to push the local commits and tags to the remote repository [Y/n]?n
The release of the source repository has been prepared successfully but the changes have not been pushed yet. After pushing the changes manually the next step will be 'bloom-release'.
```

**Comment by esteve** [comment]
@youtalk perfect, thank you so much

**Review by esteve — APPROVED** [review]
@youtalk LGTM, thanks!

**Comment by youtalk** [comment]
@esteve Great! Please approve it too😉

**Comment by esteve** [comment]
@youtalk done :sweat_smile:

**Pull request merged**
