### PR TITLE
feat(autoware_adapi_v1_msgs): add route following check option

### PR DESCRIPTION
**Pull request by isamu-takagi**
## Description

Add option for route change API. See https://github.com/autowarefoundation/autoware-documentation/pull/602 for details.

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Interface changes

None (only add message field)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by youtalk — APPROVED** [review]
LGTM

**Comment by sasakisasaki** [comment]
@isamu-takagi Thank you! Let me ask a question, does the `allow_while_using_route` have a default value, or all functions which are using this message can handle the merged message?

**Comment by isamu-takagi** [comment]
@sasakisasaki The default value is false.

**Review by sasakisasaki — APPROVED** [review]
@isamu-takagi Thank you for the answer! Then LGTM :+1:

**Pull request merged**
